/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.ComentarioData;
import AccesoADatos.EquipoMiembroData;
import AccesoADatos.TareaData;
import Entidades.Comentario;
import Entidades.EquipoMiembro;
import Entidades.Tarea;
import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thefl
 */
public class ViewTarea extends javax.swing.JInternalFrame {

    private EquipoMiembroData equipoMiembroD;
    private TareaData tareaD;
    private ComentarioData comentD;

    /**
     * Creates new form ViewTarea
     */
    public ViewTarea() {
        initComponents();
        equipoMiembroD = new EquipoMiembroData();
        tareaD = new TareaData();
        comentD = new ComentarioData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbTareas = new javax.swing.JLabel();
        lbTareaNombre = new javax.swing.JLabel();
        lbIDEM = new javax.swing.JLabel();
        lbCreacion = new javax.swing.JLabel();
        lbCierre = new javax.swing.JLabel();
        tfTareaNombre = new javax.swing.JTextField();
        tfIDEM = new javax.swing.JTextField();
        dateCreacion = new com.toedter.calendar.JDateChooser();
        dateCierre = new com.toedter.calendar.JDateChooser();
        bGuardar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbActualizarEstado = new javax.swing.JLabel();
        lbIDTarea = new javax.swing.JLabel();
        tfIDTarea = new javax.swing.JTextField();
        comboEstados = new javax.swing.JComboBox<>();
        bActualizarEstado = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lbComentario = new javax.swing.JLabel();
        lbIDTarea2 = new javax.swing.JLabel();
        tfIDTarea2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentario = new javax.swing.JTextArea();
        lbAvance = new javax.swing.JLabel();
        dateAvance = new com.toedter.calendar.JDateChooser();
        bAgregarComentario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTarea = new javax.swing.JTable();
        bListaTareas = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lbTareas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTareas.setText("Cargar una Tarea");

        lbTareaNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTareaNombre.setText("Nombre de la Tarea");

        lbIDEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIDEM.setText("N° Inscripcion");

        lbCreacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCreacion.setText("Fecha de Creacion");

        lbCierre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCierre.setText("Fecha de Cierre");

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        lbActualizarEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbActualizarEstado.setText("Actualizar estado");

        lbIDTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIDTarea.setText("N° Tarea");

        comboEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elija un estado", "Pendiente", "En Proceso", "Completada" }));

        bActualizarEstado.setText("Actualizar");
        bActualizarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarEstadoActionPerformed(evt);
            }
        });

        lbComentario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbComentario.setText("Agregar un Comentario");

        lbIDTarea2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbIDTarea2.setText("N° Tarea");

        comentario.setColumns(20);
        comentario.setRows(5);
        jScrollPane1.setViewportView(comentario);

        lbAvance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbAvance.setText("Fecha del Avance");

        bAgregarComentario.setText("Agregar");
        bAgregarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarComentarioActionPerformed(evt);
            }
        });

        tablaTarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N° Tarea", "Nombre", "N° Inscripcion", "Creacion", "Cierre"
            }
        ));
        jScrollPane3.setViewportView(tablaTarea);

        bListaTareas.setText("Lista de Tareas");
        bListaTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaTareasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bSalir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(lbTareas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bGuardar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbTareaNombre)
                                        .addComponent(lbIDEM)
                                        .addComponent(lbCreacion)
                                        .addComponent(lbCierre)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dateCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tfTareaNombre)
                                            .addComponent(tfIDEM)
                                            .addComponent(dateCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(bListaTareas)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(lbActualizarEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIDTarea)
                                .addGap(18, 18, 18)
                                .addComponent(tfIDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(comboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bActualizarEstado)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lbComentario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIDTarea2)
                                .addGap(18, 18, 18)
                                .addComponent(tfIDTarea2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lbAvance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94))))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(bAgregarComentario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTareas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTareaNombre)
                    .addComponent(tfTareaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDEM)
                    .addComponent(tfIDEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCreacion)
                    .addComponent(dateCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCierre)
                    .addComponent(dateCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bListaTareas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbActualizarEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDTarea)
                    .addComponent(tfIDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bActualizarEstado))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbComentario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbIDTarea2)
                        .addComponent(tfIDTarea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAvance))
                    .addComponent(dateAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAgregarComentario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalir)
                    .addComponent(bLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try{
        String nombre = tfTareaNombre.getText();
        int idEM = Integer.parseInt(tfIDEM.getText());
        Date fechaSql = new Date(dateCreacion.getDate().getTime());
        LocalDate creacion = fechaSql.toLocalDate();
        Date fechaSql2 = new Date(dateCierre.getDate().getTime());
        LocalDate cierre = fechaSql2.toLocalDate();
        EquipoMiembro equipoMiembroAux = equipoMiembroD.buscarEquipoMiembroPorId(idEM);
        Tarea tarea = new Tarea(equipoMiembroAux, nombre, cierre, creacion, 0);
        tareaD.guardarTarea(tarea);
        limpiar();
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR no se pudo guardar "+ex.getMessage());
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bListaTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaTareasActionPerformed
     try{
        DefaultTableModel tabla = new DefaultTableModel();
        List<Tarea> dato;
        String[] columnas = new String[5];
        tabla.addColumn("ID Tarea");
        tabla.addColumn("Nombre");
        tabla.addColumn("ID EquipoMiembro");
        tabla.addColumn("Creacion");
        tabla.addColumn("Cierre");
        dato = tareaD.listarTareas();
        for (int i = 0; i < dato.size(); i++) {
            columnas[0] = dato.get(i).getIdTarea() + "";
            columnas[1] = dato.get(i).getNombre();
            columnas[2] = dato.get(i).getMiembroEqId().getIdMiembroEq() + "";
            columnas[3] = dato.get(i).getFechaCreacion() + "";
            columnas[4] = dato.get(i).getFechaCierre() + "";
            tabla.addRow(columnas);
        }
        tablaTarea.setModel(tabla);
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR "+ex.getMessage());
        }
    }//GEN-LAST:event_bListaTareasActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bActualizarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarEstadoActionPerformed
        try{
        int id = Integer.parseInt(tfIDTarea.getText());
        String itemSeleccionado = comboEstados.getSelectedItem().toString();
        switch (itemSeleccionado) {
            case "Pendiente":
                tareaD.actualizarEstadoTarea(0, id);
                break;
            case "En Proceso":
                tareaD.actualizarEstadoTarea(1, id);
                break;
            case "Completada":
                tareaD.actualizarEstadoTarea(2, id);
                break;
        }
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR no se pudo Actualizar "+ex.getMessage());
        }
    }//GEN-LAST:event_bActualizarEstadoActionPerformed

    private void bAgregarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarComentarioActionPerformed
      try{
        int id = Integer.parseInt(tfIDTarea2.getText());
        Tarea tarrea = tareaD.buscarTareaPorId(id);
        Date fechaSql = new Date(dateAvance.getDate().getTime());
        LocalDate fecha = fechaSql.toLocalDate();
        String comenta = comentario.getText();
        Comentario coment = new Comentario(comenta, fecha, tarrea);
        comentD.guardarComentario(coment);
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR "+ex.getMessage());
        }
    }//GEN-LAST:event_bAgregarComentarioActionPerformed

    public void limpiar() {
        tfTareaNombre.setText("");
        tfIDEM.setText("");
        dateCreacion.setDate(null);
        dateCierre.setDate(null);
        tfIDTarea.setText("");
        tfIDTarea2.setText("");
        dateAvance.setDate(null);
        comentario.setText("");
        comboEstados.setSelectedIndex(0);
        DefaultTableModel tabla = new DefaultTableModel();
        List<Tarea> dato;
        String[] columnas = new String[5];
        tabla.addColumn("ID Tarea");
        tabla.addColumn("Nombre");
        tabla.addColumn("ID EquipoMiembro");
        tabla.addColumn("Creacion");
        tabla.addColumn("Cierre");
        dato = tareaD.listarTareas();
        for (int i = 0; i < dato.size(); i++) {
            columnas[0] = "";
            columnas[1] = "";
            columnas[2] = "";
            columnas[3] = "";
            columnas[4] = "";
            tabla.addRow(columnas);
        }
        tablaTarea.setModel(tabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizarEstado;
    private javax.swing.JButton bAgregarComentario;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bListaTareas;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> comboEstados;
    private javax.swing.JTextArea comentario;
    private com.toedter.calendar.JDateChooser dateAvance;
    private com.toedter.calendar.JDateChooser dateCierre;
    private com.toedter.calendar.JDateChooser dateCreacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbActualizarEstado;
    private javax.swing.JLabel lbAvance;
    private javax.swing.JLabel lbCierre;
    private javax.swing.JLabel lbComentario;
    private javax.swing.JLabel lbCreacion;
    private javax.swing.JLabel lbIDEM;
    private javax.swing.JLabel lbIDTarea;
    private javax.swing.JLabel lbIDTarea2;
    private javax.swing.JLabel lbTareaNombre;
    private javax.swing.JLabel lbTareas;
    private javax.swing.JTable tablaTarea;
    private javax.swing.JTextField tfIDEM;
    private javax.swing.JTextField tfIDTarea;
    private javax.swing.JTextField tfIDTarea2;
    private javax.swing.JTextField tfTareaNombre;
    // End of variables declaration//GEN-END:variables
}
