package Vistas;

import AccesoADatos.MiembroData;
import Entidades.Miembro;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ViewMiembro extends javax.swing.JInternalFrame {

    private MiembroData miembroD;

    public ViewMiembro() {
        initComponents();
        miembroD = new MiembroData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbMiembro = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        lbApellido = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbDNI = new javax.swing.JLabel();
        tfDNI = new javax.swing.JTextField();
        bGuardar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bActDes = new javax.swing.JButton();
        bLista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tTabla = new javax.swing.JTable();
        bLimpiar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        lbMiembro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMiembro.setText("Miembro");

        lbID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbID.setText("Numero de Miembro");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        lbApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbApellido.setText("Apellido");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombre.setText("Nombre");

        lbDNI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDNI.setText("DNI");

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        bActDes.setText("Activar | Desactivar");
        bActDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActDesActionPerformed(evt);
            }
        });

        bLista.setText("Lista");
        bLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaActionPerformed(evt);
            }
        });

        tTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Num. de Miembro", "Apellido", "Nombre", "DNI", "Estado"
            }
        ));
        jScrollPane3.setViewportView(tTabla);

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDNI)
                                            .addComponent(lbNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfNombre)
                                            .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbApellido)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(36, 36, 36)
                                                        .addComponent(lbMiembro)))
                                                .addGap(19, 19, 19))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                        .addComponent(bBuscar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(bActDes)
                                .addGap(18, 18, 18)
                                .addComponent(bGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(bLista)
                                .addGap(18, 18, 18)
                                .addComponent(bLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(bSalir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMiembro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellido)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDNI)
                    .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bSalir)
                    .addComponent(bLista)
                    .addComponent(bLimpiar)
                    .addComponent(bActDes))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        dispose();
    }//GEN-LAST:event_bSalirActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
     try{
        Miembro miembro;
        if (!tfID.getText().equals("")) {
            int id = Integer.parseInt(tfID.getText());
            miembro = miembroD.buscarMiembroPorId(id);
            tfApellido.setText(miembro.getApellido());
            tfNombre.setText(miembro.getNombre());
            tfID.setText(miembro.getIdMiembro() + "");
            tfDNI.setText(miembro.getDni() + "");
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese una ID");
        }
           } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR "+ex.getMessage());
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
  
        try{
            Miembro miembro;
        if (!tfApellido.getText().equals("")&&!tfNombre.getText().equals("")&&!tfDNI.getText().equals("")) {
            String apellido = tfApellido.getText();
            String nombre = tfNombre.getText();
            int DNI = Integer.parseInt(tfDNI.getText());
            miembro = new Miembro(DNI,nombre,apellido,true);
            miembroD.guardarMiembro(miembro);
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Alguno de los siguientes campos esta vacio: Apellido - Nombre - DNI");
        }
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR "+ex.getMessage());
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bActDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActDesActionPerformed
      try{
        if (!tfID.getText().equals("")) {
            int id = Integer.parseInt(tfID.getText());
            miembroD.activarDesactivarEstado(id);
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese una ID");
        }
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR "+ex.getMessage());
        }
    }//GEN-LAST:event_bActDesActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaActionPerformed
     try{
        DefaultTableModel tabla = new DefaultTableModel();
        List<Miembro> dato;
        String[] columnas = new String[5];
        tabla.addColumn("ID");
        tabla.addColumn("Apellido");
        tabla.addColumn("Nombre");
        tabla.addColumn("DNI");
        tabla.addColumn("Estado");
        dato = miembroD.listarMiembros();
        for (int i = 0; i < dato.size(); i++) {
            columnas[0] = dato.get(i).getIdMiembro()+"";
            columnas[1] = dato.get(i).getApellido();
            columnas[2] = dato.get(i).getNombre();
            columnas[3] = dato.get(i).getDni()+"";
            columnas[4] = dato.get(i).isEstado()+"";
            tabla.addRow(columnas);
        }
        tTabla.setModel(tabla);
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERROR "+ex.getMessage());
        }
    }//GEN-LAST:event_bListaActionPerformed

    public void limpiar(){
        tfApellido.setText("");
        tfDNI.setText("");
        tfNombre.setText("");
        tfID.setText("");
        DefaultTableModel tabla = new DefaultTableModel();
        List<Miembro> dato;
        String[] columnas = new String[5];
        tabla.addColumn("ID");
        tabla.addColumn("Apellido");
        tabla.addColumn("Nombre");
        tabla.addColumn("DNI");
        tabla.addColumn("Estado");
        dato = miembroD.listarMiembros();
        for (int i = 0; i < dato.size(); i++) {
            columnas[0] = "";
            columnas[1] = "";
            columnas[2] = "";
            columnas[3] = "";
            columnas[4] = "";
            tabla.addRow(columnas);
        }
        tTabla.setModel(tabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActDes;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bLista;
    private javax.swing.JButton bSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbDNI;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbMiembro;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTable tTabla;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
